import { DataTypes } from "sequelize";
import { sequelize } from "../db/conexion.js";


export const MarcaModel = sequelize.define(
  "marcas",
  {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
    },
    descripcion: {
        type: DataTypes.STRING,
        allowNull: false,
        },
      state: {
        type: DataTypes.BOOLEAN,
        defaultValue: true,
      }
  },
  {
    timestamps: false,
  }  
  );const marcasData = [
    { descripcion: "VOLKSWAGEN" },
    { descripcion: "RENAULT" },
    { descripcion: "FORD" },
    { descripcion: "PEUGEOT" },
    { descripcion: "ABARTH" },
    { descripcion: "AC" },
    { descripcion: "ACURA" },
    { descripcion: "ADMIRAL" },
    { descripcion: "AIWAYS" },
    { descripcion: "ALEKO" },
    { descripcion: "ALFA ROMEO" },
    { descripcion: "ALPHINA" },
    { descripcion: "ALPINE RENAULT" },
    { descripcion: "AMC" },
    { descripcion: "ASIA" },
    { descripcion: "ANADOL" },
    { descripcion: "ASTON MARTIN" },
    { descripcion: "AUDI" },
    { descripcion: "AUSTIN" },
    { descripcion: "AUTOBIANCHI" },

    { descripcion: "AUVERLAND" },
    { descripcion: "BAIC" },
    { descripcion: "BEDFORD" },
    { descripcion: "BENTLEY" },
    { descripcion: "BMW" },
    { descripcion: "BOLLORE" },
    { descripcion: "BOOM TRIKES" },
    { descripcion: "BORGWARD" },
    { descripcion: "BRILLIANCE" },
    { descripcion: "BUGATI" },
    { descripcion: "BYD" },
    { descripcion: "CANDILLAC" },
    { descripcion: "CARBODIES" },
    { descripcion: "CATERHAM" },
    { descripcion: "CHANA" },
    { descripcion: "CHANGAN" },
    { descripcion: "CHANGFENG" },
    { descripcion: "CHANGE" },
    { descripcion: "CHERY" },
    { descripcion: "CHEVROLET" },  

    { descripcion: "CHRYSLER" },
    { descripcion: "CIMA" },
    { descripcion: "CITROEN" },
    { descripcion: "CUPRA" },
    { descripcion: "DACIA" },
    { descripcion: "DADI" },
    { descripcion: "DAEWOO" },
    { descripcion: "DAIHATSU" },
    { descripcion: "DAIMLER" },
    { descripcion: "DATSUN" },
    { descripcion: "DE TOMASO" },
    { descripcion: "DELAGE" },
    { descripcion: "DELOREAN" },
    { descripcion: "DERWAYS" },
    { descripcion: "DETHLEFFS" },
    { descripcion: "DODGE" },
    { descripcion: "DONGFENG" },
    { descripcion: "DONINVEST" },
    { descripcion: "DONKERVOORT" },
    { descripcion: "DR" },
    { descripcion: "DS" },
    { descripcion: "EAGLE" },
    { descripcion: "EBRO" },
    { descripcion: "BENTLEY" },
    { descripcion: "BMW" },
    { descripcion: "BOLLORE" },
    { descripcion: "BOOM TRIKES" },
    { descripcion: "BORGWARD" },
    { descripcion: "BRILLIANCE" },
    { descripcion: "BUGATI" },
    { descripcion: "BYD" },
    { descripcion: "EFFA" },
    { descripcion: "EVOLUTE" },
    { descripcion: "EXCEED" },
    { descripcion: "FAW" },
    { descripcion: "FEBRARI" },
    { descripcion: "FIAT" },
    { descripcion: "FISHER" },
    { descripcion: "FORCE MOTORS" },
    { descripcion: "FOTON" }, 

    { descripcion: "FSO" },
    { descripcion: "FSO-POLSKI" },
    { descripcion: "FRS" },
    { descripcion: "FUSCA" },
    { descripcion: "FV FRANGIVENTO" },
    { descripcion: "GAC" },
    { descripcion: "GALLOPER" },
    { descripcion: "GAZ" },
    { descripcion: "GEELY" },
    { descripcion: "GENESIS" },
    { descripcion: "GEO" },
    { descripcion: "GINETTA" },
    { descripcion: "GM" },
    { descripcion: "GMC" },
    { descripcion: "GME" },
    { descripcion: "GOLF" },
    { descripcion: "GONOW" },
    { descripcion: "GRANDIN" },
    { descripcion: "GREAT WALL" },
    { descripcion: "GURGEL" },
    { descripcion: "HAFEI" },
    { descripcion: "HAIMA" },
    { descripcion: "HAVAL" },
    { descripcion: "HAWTAI" },
    { descripcion: "HOLDEN" },
    { descripcion: "HOMMELL" },
    { descripcion: "HUMMER" },
    { descripcion: "HUNDAI" },
    { descripcion: "INFINITI" },
    { descripcion: "INTRALL" },
    { descripcion: "IRAN KHODRO" },
    { descripcion: "ISUZU" },
    { descripcion: "IVECO" },
    { descripcion: "JAC" },
    { descripcion: "JAGUAR" },
    { descripcion: "JEEP" },
    { descripcion: "JETOUR" },
    { descripcion: "JMC" },
    { descripcion: "JOINT" },
    { descripcion: "JUNAK" }, 
    
    { descripcion: "KIA" },
    { descripcion: "LADA" },
    { descripcion: "LABOMGHINI" },
    { descripcion: "LANCIA" },
    { descripcion: "LAND ROVER" },
    { descripcion: "LANDWIND" },
    { descripcion: "LANOS" },
    { descripcion: "LDV" },
    { descripcion: "LEXUS" },
    { descripcion: "LEYLAND" },
    { descripcion: "LIFAN" },
    { descripcion: "LIGIER" },
    { descripcion: "LOTUS" },
    { descripcion: "LTI" },
    { descripcion: "LUXGEN" },
    { descripcion: "LYNK &CO" },
    { descripcion: "MAGIRUS DEUTZ" },
    { descripcion: "MAHINDRA" },
    { descripcion: "DONKERVOORT" },
    { descripcion: "MARCOS" },
    { descripcion: "MARLIN" },
    { descripcion: "MISERATI" },
    { descripcion: "MATRA" },
    { descripcion: "MAYBACH" },
    { descripcion: "MAZDA" },
    { descripcion: "MCLAREN" },
    { descripcion: "MEGA" },
    { descripcion: "MERCEDES" },
    { descripcion: "MERCEDES AMG" },
    { descripcion: "MERCEDES-BENZ" },
    { descripcion: "BMERCURYYD" },
    { descripcion: "MINAUTO" },
    { descripcion: "MINI" },
    { descripcion: "MITSUBISHI" },
    { descripcion: "MITSUOKA" },
    { descripcion: "MIURA" },
    { descripcion: "MORGAN" },
    { descripcion: "NIO" },
    { descripcion: "NISSAN" },
    { descripcion: "NYSA" },

    { descripcion: "OLDSMOBILE" },
    { descripcion: "OPEL" },
    { descripcion: "PAGANI" },
    { descripcion: "PANHARD" },
    { descripcion: "PANOZ" },
    { descripcion: "PANTHER" },
    { descripcion: "PERODUA" },
    { descripcion: "PGO" },
    { descripcion: "PLYMOUTH" },
    { descripcion: "POLESTAR" },
    { descripcion: "POLONEZ" },
    { descripcion: "PONTIAC" },
    { descripcion: "PORSCHE" },
    { descripcion: "PROTON" },
    { descripcion: "PÖSSL" },
    { descripcion: "QOROS" },
    { descripcion: "QUANTUM" },
    { descripcion: "RAM" },
    { descripcion: "RANGE ROVER" },
    { descripcion: "RAVON" },
    { descripcion: "RELIANT" },
    { descripcion: "ROEWE" },
    { descripcion: "ROLLS-ROYCE" },
    { descripcion: "ROVER" },
    { descripcion: "SAAB" },
    { descripcion: "SAIPA" },
    { descripcion: "SALEEN" },
    { descripcion: "SAMAND" },
    { descripcion: "SANSUNG" },
    { descripcion: "SANTANA" },
    { descripcion: "SATURN" },
    { descripcion: "SCION" },
    { descripcion: "SETRA" },
    { descripcion: "SHINERAY" },
    { descripcion: "SHUANGHUAN" },
    { descripcion: "SIMCA" },
    { descripcion: "SIN" },
    { descripcion: "SKODA" },
    { descripcion: "SMA" },
    { descripcion: "SMART" },

    { descripcion: "SPYKER" },
    { descripcion: "SSANGYONG" },
    { descripcion: "SUBARU" },
    { descripcion: "SUNDEAM" },
    { descripcion: "SUV LEXUS" },
    { descripcion: "SUZUKI" },
    { descripcion: "SYRENA" },
    { descripcion: "TAGAZ" },
    { descripcion: "TAGAZ VEGA" },
    { descripcion: "TALBOT" },
    { descripcion: "TATA" },
    { descripcion: "TAZZARI" },
    { descripcion: "TESLA" },
    { descripcion: "THINIK" },
    { descripcion: "TIANMA" },
    { descripcion: "TIAYE" },
    { descripcion: "TOFAS" },
    { descripcion: "TOYOTA" },
    { descripcion: "TRABANT" },
    { descripcion: "TRIUMPH" },
    { descripcion: "TROLLER" },
    { descripcion: "TVR" },
    { descripcion: "TWIKE" },
    { descripcion: "UMM" },
    { descripcion: "VAUXHALL" },
    { descripcion: "VENTURI" },
    { descripcion: "VOLVO" },
    { descripcion: "VORTEX" },
    { descripcion: "WARSZAWA" },
    { descripcion: "WIESMANN" },
    { descripcion: "WILLYS" },
    { descripcion: "XIN KAI" },
    { descripcion: "XPENG" },
    { descripcion: "YOGOMO" },
    { descripcion: "YZK" },
    { descripcion: "ZASTAVA" },
    { descripcion: "ZOTYE" },
    { descripcion: "ZX" },
    { descripcion: "BA3" },
    { descripcion: "BE" },
                
    // Agrega más objetos para insertar más datos
  ];
  async function seed() {
    try {
      await sequelize.sync({ force: false }); // Esto eliminará y recreará la tabla (ten cuidado en producción)
  
      for (const marcaData of marcasData) {
        await MarcaModel.create(marcaData);
      }
  
      console.log("Datos de marcas insertados con éxito.");
    } catch (error) {
      console.error("Error al insertar datos de marcas:", error);
    } finally {
      //sequelize.close(); // Cierra la conexión a la base de datos al finalizar
    }
  }
  
  seed();